package com.cooksys.day4.Maven.test;

import static org.junit.Assert.*;

import org.junit.*;

import com.cooksys.day4.Maven.App;

import static com.cooksys.day4.Maven.App.Log;

public class LoggerTest {

	@Test
	public void test() {	
		Log.trace("aspect-oriented autogenerated style trace messages");
		Log.debug("debug");
		
		Log.info(Log.getName());

		Log.warn("warning");
		Log.error("error");

		assertTrue("Log not a logger", Log.getName() == App.class.getName() );
	}

}
